- name: Configuration des interfaces et DHCP (1.1 à 1.2)
  hosts: csr1000
  gather_facts: no

  tasks:
    # Interfaces
    - name: Configurer GigabitEthernet1 (WAN DHCP)
      cisco.ios.ios_l3_interfaces:
          config:
            - name: GigabitEthernet2
              ipv4:
                - address: 192.168.2.1/24
