- name: Configuration des interfaces (1.1) et DHCP (1.2)
  hosts: csr1000
  gather_facts: no
  connection: network_cli

  tasks:

    # -------------------------
    # 1.1 - Interface WAN (DHCP)
    # -------------------------
    - name: Configurer GigabitEthernet1 (WAN DHCP)
      cisco.ios.ios_config:
        lines:
          - ip address dhcp
          - no shutdown
          - description WAN DHCP
        parents: interface GigabitEthernet1

    # -------------------------
    # 1.1 - Interfaces LAN (statique)
    # -------------------------
    - name: Configurer GigabitEthernet2, 3 et 4 avec IP statique (sans desc ni enabled)
      cisco.ios.ios_l3_interfaces:
        config:
          - name: GigabitEthernet2
            ipv4:
              - address: 192.168.2.1/24
             

          - name: GigabitEthernet3
            ipv4:
              - address: 192.168.3.1/24
             
          - name: GigabitEthernet4
            ipv4:
              - address: 192.168.4.1/24
             
        state: merged

    # -------------------------
    # 1.2 - DHCP Server
    # -------------------------
    - name: Supprimer le pool DHCP existant (si présent)
      cisco.ios.ios_config:
        lines:
          - no ip dhcp pool LAN_POOL

    - name: Créer un pool DHCP pour le LAN (GigabitEthernet2)
      cisco.ios.ios_config:
        lines:
          - ip dhcp pool LAN_POOL
          - network 192.168.2.0 255.255.255.0
          - default-router 192.168.2.1
          - dns-server 8.8.8.8
