- name: Configuration des interfaces du routeur CSR1000
  hosts: csr1000
  gather_facts: no

  tasks:
    - name: Configurer GigabitEthernet1 (DHCP)
      cisco.ios.ios_config:
        lines:
          - ip address dhcp
          - no shutdown
          - description WAN DHCP
        parents: interface GigabitEthernet1

    - name: Configurer GigabitEthernet2 (192.168.2.1/24)
      cisco.ios.ios_config:
        lines:
          - ip address 192.168.2.1 255.255.255.0
          - no shutdown
          - description LAN 1
        parents: interface GigabitEthernet2

    - name: Configurer GigabitEthernet3 (192.168.3.1/24)
      cisco.ios.ios_config:
        lines:
          - ip address 192.168.3.1 255.255.255.0
          - no shutdown
          - description DMZ
        parents: interface GigabitEthernet3

    - name: Configurer GigabitEthernet4 (192.168.4.1/24)
      cisco.ios.ios_config:
        lines:
          - ip address 192.168.4.1 255.255.255.0
          - no shutdown
          - description ADMIN
        parents: interface GigabitEthernet4
- name: Configuration des interfaces et du DHCP sur le routeur CSR1000
  hosts: csr1000
  gather_facts: no

  tasks:
    # -------------------------
    # Question 1.1 - Interfaces
    # -------------------------
    - name: Configurer GigabitEthernet1 (DHCP)
      cisco.ios.ios_config:
        lines:
          - ip address dhcp
          - no shutdown
          - description WAN DHCP
        parents: interface GigabitEthernet1

    - name: Configurer GigabitEthernet2 (192.168.2.1/24)
      cisco.ios.ios_config:
        lines:
          - ip address 192.168.2.1 255.255.255.0
          - no shutdown
          - description LAN 1
        parents: interface GigabitEthernet2

    - name: Configurer GigabitEthernet3 (192.168.3.1/24)
      cisco.ios.ios_config:
        lines:
          - ip address 192.168.3.1 255.255.255.0
          - no shutdown
          - description DMZ
        parents: interface GigabitEthernet3

    - name: Configurer GigabitEthernet4 (192.168.4.1/24)
      cisco.ios.ios_config:
        lines:
          - ip address 192.168.4.1 255.255.255.0
          - no shutdown
          - description ADMIN
        parents: interface GigabitEthernet4

    # -------------------------
    # Question 1.2 - DHCP
    # -------------------------
    - name: Supprimer le pool DHCP existant (si présent)
      cisco.ios.ios_config:
        lines:
          - no ip dhcp pool LAN_POOL

    - name: Créer un pool DHCP pour le LAN
      cisco.ios.ios_config:
        lines:
          - ip dhcp pool LAN_POOL
          - network 192.168.2.0 255.255.255.0
          - default-router 192.168.2.1
          
