- name: Configuration des interfaces et DHCP (1.1 à 1.2)
  hosts: csr1000
  gather_facts: no

  tasks:
    # Interfaces
    - name: Configurer GigabitEthernet1 (WAN DHCP)
      cisco.ios.ios_config:
        lines:
          - ip address dhcp
          - no shutdown
          - description WAN DHCP
        parents: interface GigabitEthernet1

    - name: Configurer GigabitEthernet2 (LAN 1)
      cisco.ios.ios_config:
        lines:
          - ip address 192.168.2.1 255.255.255.0
          - no shutdown
          - description LAN 1
        parents: interface GigabitEthernet2

    - name: Configurer GigabitEthernet3 (DMZ)
      cisco.ios.ios_config:
        lines:
          - ip address 192.168.3.1 255.255.255.0
          - no shutdown
          - description DMZ
        parents: interface GigabitEthernet3

    - name: Configurer GigabitEthernet4 (ADMIN)
      cisco.ios.ios_config:
        lines:
          - ip address 192.168.4.1 255.255.255.0
          - no shutdown
          - description ADMIN
        parents: interface GigabitEthernet4

    # DHCP
    - name: Supprimer le pool DHCP existant
      cisco.ios.ios_config:
        lines:
          - no ip dhcp pool LAN_POOL

    - name: Créer un pool DHCP pour le LAN
      cisco.ios.ios_config:
        lines:
          - ip dhcp pool LAN_POOL
          - network 192.168.2.0 255.255.255.0
          - default-router 192.168.2.1
          - dns-server 8.8.8.8
